schema_version = 1
id = "com.github.ayn2op.zed-horizon"
name = "Horizon"
version = "0.1.0"
authors = ["ayn2op <ayn2op@gmail.com>"]
description = "Horizon theme for Zed"
repository = "https://github.com/ayn2op/zed-horizon"
